/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It should not be edited manually.

// ──────────────────────────────────────────────────────────────────────────────
// Import Routes
// ──────────────────────────────────────────────────────────────────────────────

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LoginImport } from './routes/login'
import { Route as RegisterImport } from './routes/register'
import { Route as TrackImport } from './routes/track'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardShipmentsNewImport } from './routes/dashboard/shipments/new'
import { Route as DashboardShipmentsIdImport } from './routes/dashboard/shipments/$id'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminShipmentsIndexImport } from './routes/admin/shipments/index'
import { Route as AdminShipmentsIdImport } from './routes/admin/shipments/$id'
import { Route as AdminUsersIndexImport } from './routes/admin/users/index'

// ──────────────────────────────────────────────────────────────────────────────
// Create/Update Routes
// ──────────────────────────────────────────────────────────────────────────────

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const TrackRoute = TrackImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardShipmentsNewRoute = DashboardShipmentsNewImport.update({
  id: '/dashboard/shipments/new',
  path: '/dashboard/shipments/new',
  getParentRoute: () => rootRoute,
} as any)

const DashboardShipmentsIdRoute = DashboardShipmentsIdImport.update({
  id: '/dashboard/shipments/$id',
  path: '/dashboard/shipments/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const AdminShipmentsIndexRoute = AdminShipmentsIndexImport.update({
  id: '/admin/shipments/',
  path: '/admin/shipments/',
  getParentRoute: () => rootRoute,
} as any)

const AdminShipmentsIdRoute = AdminShipmentsIdImport.update({
  id: '/admin/shipments/$id',
  path: '/admin/shipments/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRoute,
} as any)

// ──────────────────────────────────────────────────────────────────────────────
// Route Tree
// ──────────────────────────────────────────────────────────────────────────────

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexImport
    parentRoute: typeof rootRoute
  }
  '/login': {
    id: '/login'
    path: '/login'
    fullPath: '/login'
    preLoaderRoute: typeof LoginImport
    parentRoute: typeof rootRoute
  }
  '/register': {
    id: '/register'
    path: '/register'
    fullPath: '/register'
    preLoaderRoute: typeof RegisterImport
    parentRoute: typeof rootRoute
  }
  '/track': {
    id: '/track'
    path: '/track'
    fullPath: '/track'
    preLoaderRoute: typeof TrackImport
    parentRoute: typeof rootRoute
  }
  '/dashboard/': {
    id: '/dashboard/'
    path: '/dashboard/'
    fullPath: '/dashboard/'
    preLoaderRoute: typeof DashboardIndexImport
    parentRoute: typeof rootRoute
  }
  '/dashboard/shipments/new': {
    id: '/dashboard/shipments/new'
    path: '/dashboard/shipments/new'
    fullPath: '/dashboard/shipments/new'
    preLoaderRoute: typeof DashboardShipmentsNewImport
    parentRoute: typeof rootRoute
  }
  '/dashboard/shipments/$id': {
    id: '/dashboard/shipments/$id'
    path: '/dashboard/shipments/$id'
    fullPath: '/dashboard/shipments/$id'
    preLoaderRoute: typeof DashboardShipmentsIdImport
    parentRoute: typeof rootRoute
  }
  '/admin/': {
    id: '/admin/'
    path: '/admin/'
    fullPath: '/admin/'
    preLoaderRoute: typeof AdminIndexImport
    parentRoute: typeof rootRoute
  }
  '/admin/shipments/': {
    id: '/admin/shipments/'
    path: '/admin/shipments/'
    fullPath: '/admin/shipments/'
    preLoaderRoute: typeof AdminShipmentsIndexImport
    parentRoute: typeof rootRoute
  }
  '/admin/shipments/$id': {
    id: '/admin/shipments/$id'
    path: '/admin/shipments/$id'
    fullPath: '/admin/shipments/$id'
    preLoaderRoute: typeof AdminShipmentsIdImport
    parentRoute: typeof rootRoute
  }
  '/admin/users/': {
    id: '/admin/users/'
    path: '/admin/users/'
    fullPath: '/admin/users/'
    preLoaderRoute: typeof AdminUsersIndexImport
    parentRoute: typeof rootRoute
  }
}

// Augment the router-core module so createFileRoute path strings are validated
declare module '@tanstack/router-core' {
  interface FileRoutesByPath extends FileRoutesByPath {} // eslint-disable-line @typescript-eslint/no-empty-interface
}

export type RootRouteChildren = {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TrackRoute: typeof TrackRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardShipmentsNewRoute: typeof DashboardShipmentsNewRoute
  DashboardShipmentsIdRoute: typeof DashboardShipmentsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminShipmentsIndexRoute: typeof AdminShipmentsIndexRoute
  AdminShipmentsIdRoute: typeof AdminShipmentsIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  LoginRoute,
  RegisterRoute,
  TrackRoute,
  DashboardIndexRoute,
  DashboardShipmentsNewRoute,
  DashboardShipmentsIdRoute,
  AdminIndexRoute,
  AdminShipmentsIndexRoute,
  AdminShipmentsIdRoute,
  AdminUsersIndexRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addRouteTypes<{
  fileRoutesByPath: FileRoutesByPath
}>()
